name = "chzzk-roulette"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]
